import Head from 'next/head';
import { ReactNode } from 'react';

import BaseLayout from '@/Layouts/BaseLayout';

export default function Home() {
    return (
        <>
            <Head>
                <title>Share Trip E-Commerce</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-auto w-[1112px]  py-8">
                <div className="flex w-full flex-row justify-between">
                    {[1, 2, 3, 4, 5].map((index) => (
                        <div className="group w-[210px]" key={index}>
                            <div className=" z-0 h-[332px]   bg-[url('/assets/tshirt-01.png')] ">
                                <div className="invisible z-10 flex h-full w-full flex-row items-end justify-center gap-x-[10px] bg-black bg-opacity-50 pb-[30px] text-[20px] text-white group-hover:visible ">
                                    <a className="flex h-[41px] w-[41px] flex-row items-center justify-center rounded-md border-2 border-[#ADADAD] hover:bg-white  hover:text-[#000] ">
                                        <p>icon</p>
                                    </a>
                                    <a className="flex h-[41px] w-[41px] flex-row items-center justify-center rounded-md border-2 border-[#ADADAD] hover:bg-white  hover:text-[#000]">
                                        <p>icon</p>
                                    </a>
                                </div>
                            </div>
                            <div>
                                <span className="text-[14px] font-light text-[#5A6573]">Fablife</span>
                                <h3 className="text-[16px] font-bold text-black">
                                    Fablife Mens Premiu Designer Edition T Shirt
                                </h3>
                                <span className="flex flex-row">
                                    <p className="text-[20px] font-bold text-[#1882FF]">$ 2500</p>
                                    <p className="ml-[10px] text-[20px] font-normal text-[#77818C] line-through">
                                        $ 2500
                                    </p>
                                </span>
                            </div>
                        </div>
                    ))}
                </div>
            </main>
        </>
    );
}

Home.getLayout = (page: ReactNode) => {
    return <BaseLayout>{page}</BaseLayout>;
};
